In [1]:
import pickle
import pandas as pd

with open('../iters_0-1999.pickle','rb') as f:
    iters = pickle.load(f)

with open('../iters_0-2999_run2.pickle','rb') as f:
    iters_r2 = pickle.load(f)

dfs = []
for i,df in enumerate(iters+iters_r2):
    df['Win'] = df.Pos.apply(lambda x: 1 if x==1 else 0)
    df['DNF'] = (1-df.Finished)
    df['Pole'] = df.SP.apply(lambda x: 1 if x==1 else 0)
    df['Indy500Winner'] = ((df.RaceInSeason ==7) & (df.Pos ==1)).astype(int)
    df_agg = df.groupby('Driver').agg(
        Pts = ('Pts','sum'),
        AvgSP = ('SP','mean'),
        FinishPct = ('Finished','mean'),
        AvgPos = ('Pos','mean'),
        Wins = ('Win','sum'),
        Indy500Winner = ('Indy500Winner','max'),
        DNFs = ('DNF','sum'),
        Poles = ('Pole','sum')
    ).reset_index()
    df_agg['Rank'] = df_agg['Pts'].rank(ascending=False)
    df_agg['iter'] = str(i)
    df_agg['Champion'] = (df_agg['Rank'] == 1).astype(int)
    dfs.append(df_agg)

dfa = pd.concat(dfs)

In [2]:
dfa.groupby('Driver').agg(
        Avg_Pts = ('Pts','mean'),
        FinishRate = ('FinishPct','mean'),
        AvgSP = ('AvgSP','mean'),
        AvgFP = ('AvgPos','mean'),
        AvgWins = ('Wins','mean'),
        AvgPoles = ('Poles','mean'),
        AvgStandings = ('Rank','mean'),
        Championships = ('Champion','sum'),
        Indy500Wins = ('Indy500Winner','sum'),
        Best = ('Rank','min'),
        Worst = ('Rank','max'),
        
).sort_values('AvgStandings')

,Avg_Pts,FinishRate,AvgSP,AvgFP,AvgWins,AvgPoles,AvgStandings,Championships,Indy500Wins,Best,Worst
Driver,,,,,,,,,,,
"Palou, Alex",644.542998,0.853422,5.180067,6.868256,4.3862,3.5678,1.4792,3412,1014,1.0,9.0
"O'Ward, Pato",587.908658,0.850600,5.515422,7.593044,2.5350,4.0560,2.3534,1225,1033,1.0,12.0
"Lundgaard, Christian",503.868111,0.852411,8.029389,9.255433,1.2204,1.6582,4.8102,124,433,1.0,20.0
"McLaughlin, Scott",501.387259,0.852511,9.311089,10.092133,1.9534,1.4182,5.1412,167,193,1.0,21.0
"Dixon, Scott",468.486705,0.854456,12.362689,10.106767,0.7424,0.2304,6.4658,23,212,1.0,21.0
"Malukas, David",451.926165,0.850322,8.430344,11.294733,1.1294,1.6130,7.6822,26,307,1.0,23.0
"Kirkwood, Kyle",444.205517,0.852822,10.574000,11.020400,0.8866,0.7356,8.0330,9,126,1.0,22.0
"Newgarden, Josef",438.124189,0.848800,10.524233,11.574111,0.9934,0.9362,8.5396,8,40,1.0,22.0
"Armstrong, Marcus",420.497024,0.853100,9.592167,11.625944,0.5478,0.5658,9.6392,5,154,1.0,22.0
"Rossi, Alexander",401.221846,0.848678,12.769044,12.238700,0.5342,0.2530,11.1482,1,257,1.0,23.0
"Rosenqvist, Felix",392.887067,0.851389,9.204767,12.370467,0.3122,1.0280,11.8046,0,90,2.0,22.0
"Simpson, Kyffin",391.086263,0.850411,14.254711,12.527656,0.4090,0.0916,11.9582,0,121,2.0,22.0
"Ferrucci, Santino",381.449506,0.849244,15.452878,12.924178,0.5240,0.4942,12.7842,0,278,2.0,23.0
"Rasmussen, Christian",378.650426,0.850933,15.740078,12.941322,0.4456,0.0418,13.0046,0,183,2.0,24.0
"Siegel, Nolan",362.132762,0.845211,11.183867,13.365378,0.2286,0.4814,14.4620,0,64,2.0,22.0
"Ericsson, Marcus",347.775006,0.849489,12.397344,13.898544,0.1968,0.2424,15.7062,0,45,2.0,25.0
"Veekay, Rinus",345.232763,0.849711,16.403022,14.268633,0.4156,0.1334,15.8564,0,159,3.0,25.0
"Grosjean, Romain",338.388682,0.841311,13.777233,14.238156,0.1780,0.1016,16.4668,0,24,4.0,24.0
"Power, Will",331.388685,0.848989,13.334633,14.427833,0.1300,0.0732,17.0936,0,26,3.0,23.0
"Robb, Sting Ray",324.575787,0.848200,19.337122,14.760600,0.1742,0.0000,17.6006,0,68,5.0,25.0
"Rahal, Graham",296.794507,0.851744,14.531500,15.619056,0.0226,0.2084,19.7608,0,2,8.0,25.0
"Foster, Louis",272.594603,0.841111,17.952611,16.380278,0.0000,0.0000,21.3254,0,0,14.0,25.0
"Schumacher, Mick",227.741230,0.830900,18.564256,18.627133,0.0000,0.0000,23.2896,0,0,20.0,25.0
"Collet, Caio",208.345814,0.814589,20.124889,19.716167,0.0006,0.0090,24.2724,0,1,21.0,25.0
"Hauger, Denis",207.520472,0.811700,22.920467,19.704244,0.0000,0.0000,24.3226,0,0,20.0,25.0
"Carpenter, Ed",19.357439,0.763200,10.698400,15.170200,0.0150,0.0416,27.2436,0,75,26.0,29.0
"Hunter-Reay, Ryan",18.382365,0.759400,13.710400,15.313200,0.0122,0.0130,27.3362,0,61,26.0,29.0
"Castroneves, Helio",17.895908,0.769000,15.149000,15.707000,0.0068,0.0062,27.3508,0,34,26.0,29.0
"Harvey, Jack",12.195986,0.772800,26.021400,19.904600,0.0000,0.0000,28.0694,0,0,26.0,29.0

In [3]:
with open('../iters_0-2499_with_comps.pickle','rb') as f:
    iters_wc = pickle.load(f)

with open('../iters_0-2499_with_comps_run2.pickle','rb') as f:
    iters_wcr2 = pickle.load(f)

dfs2 = []
for i,df in enumerate(iters_wc+iters_wcr2):
    df['Win'] = df.Pos.apply(lambda x: 1 if x==1 else 0)
    df['DNF'] = (1-df.Finished)
    df['Pole'] = df.SP.apply(lambda x: 1 if x==1 else 0)
    df['Indy500Winner'] = ((df.RaceInSeason ==7) & (df.Pos ==1)).astype(int)
    df_agg = df.groupby('Driver').agg(
        Pts = ('Pts','sum'),
        AvgSP = ('SP','mean'),
        FinishPct = ('Finished','mean'),
        AvgPos = ('Pos','mean'),
        Wins = ('Win','sum'),
        Indy500Winner = ('Indy500Winner','max'),
        DNFs = ('DNF','sum'),
        Poles = ('Pole','sum')
    ).reset_index()
    df_agg['Rank'] = df_agg['Pts'].rank(ascending=False)
    df_agg['iter'] = f'{i}_wc'
    df_agg['Champion'] = (df_agg['Rank'] == 1).astype(int)
    dfs2.append(df_agg)

dfa2 = pd.concat(dfs2)

In [4]:
dfa2.groupby('Driver').agg(
        Avg_Pts = ('Pts','mean'),
        FinishRate = ('FinishPct','mean'),
        AvgSP = ('AvgSP','mean'),
        AvgFP = ('AvgPos','mean'),
        AvgWins = ('Wins','mean'),
        AvgPoles = ('Poles','mean'),
        AvgStandings = ('Rank','mean'),
        Championships = ('Champion','sum'),
        Indy500Wins = ('Indy500Winner','sum'),
        Best = ('Rank','min'),
        Worst = ('Rank','max')
).sort_values('AvgStandings')

,Avg_Pts,FinishRate,AvgSP,AvgFP,AvgWins,AvgPoles,AvgStandings,Championships,Indy500Wins,Best,Worst
Driver,,,,,,,,,,,
"Palou, Alex",643.018262,0.852844,5.154867,6.934922,4.3922,3.6076,1.5102,3354,1028,1.0,15.0
"O'Ward, Pato",586.995516,0.852667,5.537822,7.615378,2.5434,3.9836,2.3222,1281,1014,1.0,16.0
"Lundgaard, Christian",501.495478,0.850522,8.075567,9.366044,1.2456,1.6572,4.7748,125,446,1.0,19.0
"McLaughlin, Scott",498.454797,0.852933,9.339456,10.185911,1.9242,1.3964,5.0954,171,190,1.0,20.0
"Dixon, Scott",463.664365,0.852733,12.422044,10.257644,0.7152,0.2228,6.6060,22,202,1.0,21.0
"Malukas, David",448.782284,0.850867,8.488144,11.417533,1.1266,1.6308,7.7064,22,291,1.0,23.0
"Kirkwood, Kyle",438.050519,0.850467,10.608567,11.233767,0.8642,0.7248,8.2390,13,115,1.0,23.0
"Newgarden, Josef",436.314641,0.849933,10.548633,11.630533,0.9690,0.9208,8.4412,9,59,1.0,23.0
"Armstrong, Marcus",417.530514,0.853489,9.632211,11.756356,0.5514,0.5452,9.6316,1,139,1.0,23.0
"Rossi, Alexander",399.296375,0.851667,12.766578,12.335567,0.5586,0.2460,11.0614,1,273,1.0,24.0
"Rosenqvist, Felix",391.825956,0.851989,9.188533,12.438033,0.3198,1.0290,11.6182,0,86,2.0,23.0
"Simpson, Kyffin",388.946079,0.851000,14.264178,12.631422,0.4064,0.0924,11.9046,0,100,2.0,24.0
"Ferrucci, Santino",376.976588,0.850133,15.421633,13.097111,0.5044,0.4852,12.8974,1,272,1.0,25.0
"Rasmussen, Christian",374.724790,0.849211,15.687100,13.115856,0.4320,0.0476,13.0692,0,180,2.0,25.0
"Siegel, Nolan",358.843629,0.848733,11.218144,13.505356,0.2262,0.5096,14.4270,0,84,3.0,24.0
"Ericsson, Marcus",343.244073,0.849478,12.411111,14.086233,0.1880,0.2566,15.7946,0,41,3.0,25.0
"Veekay, Rinus",341.708404,0.852256,16.341433,14.431989,0.4286,0.1330,15.9176,0,181,3.0,25.0
"Grosjean, Romain",335.447439,0.843078,13.818511,14.388211,0.1978,0.0972,16.4876,0,29,4.0,25.0
"Power, Will",327.384996,0.850678,13.345011,14.600800,0.1212,0.0744,17.1888,0,22,4.0,25.0
"Robb, Sting Ray",321.144259,0.847833,19.217733,14.923233,0.1772,0.0000,17.6866,0,64,3.0,25.0
"Rahal, Graham",292.197943,0.851689,14.495656,15.837444,0.0226,0.2094,20.0300,0,1,8.0,25.0
"Foster, Louis",267.307647,0.841844,17.919244,16.640856,0.0002,0.0000,21.8698,0,0,13.0,25.0
"Collet, Caio",244.332202,0.814467,19.379144,18.151222,0.0336,0.0406,23.2268,0,10,12.0,25.0
"Schumacher, Mick",239.802476,0.829467,18.863900,18.234400,0.0110,0.0200,23.5356,0,3,16.0,25.0
"Hauger, Denis",232.143323,0.812222,23.310833,18.582567,0.0068,0.0000,23.9580,0,1,15.0,25.0
"Carpenter, Ed",19.138528,0.767000,10.889200,15.323400,0.0164,0.0440,27.2330,0,82,26.0,29.0
"Hunter-Reay, Ryan",18.421040,0.754200,13.288200,15.412800,0.0108,0.0208,27.3120,0,54,26.0,29.0
"Castroneves, Helio",17.412012,0.764200,15.655600,15.997400,0.0066,0.0050,27.3772,0,33,26.0,29.0
"Harvey, Jack",11.959609,0.773600,25.958000,20.095400,0.0000,0.0000,28.0778,0,0,26.0,29.0

In [5]:
df_all = pd.concat([dfa,dfa2])
df_all['FinishPct2'] = df_all['FinishPct']*100
print(df_all.groupby('Driver').agg(
        Avg_Pts = ('Pts','mean'),
        FinishRate = ('FinishPct2','mean'),
        AvgSP = ('AvgSP','mean'),
        AvgFP = ('AvgPos','mean'),
        AvgWins = ('Wins','mean'),
        AvgPoles = ('Poles','mean'),
).sort_values('Avg_Pts',ascending=False).round(1).to_markdown())
print(df_all.groupby('Driver').agg(
        AvgStandings = ('Rank','mean'),
        Championships = ('Champion','sum'),
        Indy500Wins = ('Indy500Winner','sum'),
        Best = ('Rank','min'),
        Worst = ('Rank','max')
).sort_values('AvgStandings').round(1).to_markdown())

| Driver               |   Avg_Pts |   FinishRate |   AvgSP |   AvgFP |   AvgWins |   AvgPoles |
|:---------------------|----------:|-------------:|--------:|--------:|----------:|-----------:|
| Palou, Alex          |     643.8 |         85.3 |     5.2 |     6.9 |       4.4 |        3.6 |
| O'Ward, Pato         |     587.5 |         85.2 |     5.5 |     7.6 |       2.5 |        4   |
| Lundgaard, Christian |     502.7 |         85.1 |     8.1 |     9.3 |       1.2 |        1.7 |
| McLaughlin, Scott    |     499.9 |         85.3 |     9.3 |    10.1 |       1.9 |        1.4 |
| Dixon, Scott         |     466.1 |         85.4 |    12.4 |    10.2 |       0.7 |        0.2 |
| Malukas, David       |     450.4 |         85.1 |     8.5 |    11.4 |       1.1 |        1.6 |
| Kirkwood, Kyle       |     441.1 |         85.2 |    10.6 |    11.1 |       0.9 |        0.7 |
| Newgarden, Josef     |     437.2 |         84.9 |    10.5 |    11.6 |       1   |        0.9 |
| Armstrong, Marcus    |     419   |         85.3 |     9.6 |    11.7 |       0.5 |        0.6 |
| Rossi, Alexander     |     400.3 |         85   |    12.8 |    12.3 |       0.5 |        0.2 |
| Rosenqvist, Felix    |     392.4 |         85.2 |     9.2 |    12.4 |       0.3 |        1   |
| Simpson, Kyffin      |     390   |         85.1 |    14.3 |    12.6 |       0.4 |        0.1 |
| Ferrucci, Santino    |     379.2 |         85   |    15.4 |    13   |       0.5 |        0.5 |
| Rasmussen, Christian |     376.7 |         85   |    15.7 |    13   |       0.4 |        0   |
| Siegel, Nolan        |     360.5 |         84.7 |    11.2 |    13.4 |       0.2 |        0.5 |
| Ericsson, Marcus     |     345.5 |         84.9 |    12.4 |    14   |       0.2 |        0.2 |
| Veekay, Rinus        |     343.5 |         85.1 |    16.4 |    14.4 |       0.4 |        0.1 |
| Grosjean, Romain     |     336.9 |         84.2 |    13.8 |    14.3 |       0.2 |        0.1 |
| Power, Will          |     329.4 |         85   |    13.3 |    14.5 |       0.1 |        0.1 |
| Robb, Sting Ray      |     322.9 |         84.8 |    19.3 |    14.8 |       0.2 |        0   |
| Rahal, Graham        |     294.5 |         85.2 |    14.5 |    15.7 |       0   |        0.2 |
| Foster, Louis        |     270   |         84.1 |    17.9 |    16.5 |       0   |        0   |
| Schumacher, Mick     |     233.8 |         83   |    18.7 |    18.4 |       0   |        0   |
| Collet, Caio         |     226.3 |         81.5 |    19.8 |    18.9 |       0   |        0   |
| Hauger, Denis        |     219.8 |         81.2 |    23.1 |    19.1 |       0   |        0   |
| Carpenter, Ed        |      19.2 |         76.5 |    10.8 |    15.2 |       0   |        0   |
| Hunter-Reay, Ryan    |      18.4 |         75.7 |    13.5 |    15.4 |       0   |        0   |
| Castroneves, Helio   |      17.7 |         76.7 |    15.4 |    15.9 |       0   |        0   |
| Harvey, Jack         |      12.1 |         77.3 |    26   |    20   |       0   |        0   |
| Driver               |   AvgStandings |   Championships |   Indy500Wins |   Best |   Worst |
|:---------------------|---------------:|----------------:|--------------:|-------:|--------:|
| Palou, Alex          |            1.5 |            6766 |          2042 |      1 |      15 |
| O'Ward, Pato         |            2.3 |            2506 |          2047 |      1 |      16 |
| Lundgaard, Christian |            4.8 |             249 |           879 |      1 |      20 |
| McLaughlin, Scott    |            5.1 |             338 |           383 |      1 |      21 |
| Dixon, Scott         |            6.5 |              45 |           414 |      1 |      21 |
| Malukas, David       |            7.7 |              48 |           598 |      1 |      23 |
| Kirkwood, Kyle       |            8.1 |              22 |           241 |      1 |      23 |
| Newgarden, Josef     |            8.5 |              17 |            99 |      1 |      23 |
| Armstrong, Marcus    |            9.6 |               6 |           293 |      1 |      23 |
| Rossi, Alexander     |           11.1 |               2 |           530 |      1 |      24 |
| Rosenqvist, Felix    |           11.7 |               0 |           176 |      2 |      23 |
| Simpson, Kyffin      |           11.9 |               0 |           221 |      2 |      24 |
| Ferrucci, Santino    |           12.8 |               1 |           550 |      1 |      25 |
| Rasmussen, Christian |           13   |               0 |           363 |      2 |      25 |
| Siegel, Nolan        |           14.4 |               0 |           148 |      2 |      24 |
| Ericsson, Marcus     |           15.8 |               0 |            86 |      2 |      25 |
| Veekay, Rinus        |           15.9 |               0 |           340 |      3 |      25 |
| Grosjean, Romain     |           16.5 |               0 |            53 |      4 |      25 |
| Power, Will          |           17.1 |               0 |            48 |      3 |      25 |
| Robb, Sting Ray      |           17.6 |               0 |           132 |      3 |      25 |
| Rahal, Graham        |           19.9 |               0 |             3 |      8 |      25 |
| Foster, Louis        |           21.6 |               0 |             0 |     13 |      25 |
| Schumacher, Mick     |           23.4 |               0 |             3 |     16 |      25 |
| Collet, Caio         |           23.7 |               0 |            11 |     12 |      25 |
| Hauger, Denis        |           24.1 |               0 |             1 |     15 |      25 |
| Carpenter, Ed        |           27.2 |               0 |           157 |     26 |      29 |
| Hunter-Reay, Ryan    |           27.3 |               0 |           115 |     26 |      29 |
| Castroneves, Helio   |           27.4 |               0 |            67 |     26 |      29 |
| Harvey, Jack         |           28.1 |               0 |             0 |     26 |      29 |

In [6]:
weird_iters = df_all.loc[(df_all.Champion == 1) & df_all.Driver.isin(['Ferrucci, Santino','Rossi, Alexander','Armstrong, Marcus']),'iter']

In [10]:
for i in list(weird_iters):
    print(df_all.loc[df_all.iter == i].sort_values(['Pts'],ascending=False)['Driver'].reset_index(drop=True))

0        Armstrong, Marcus
1             O'Ward, Pato
2           Kirkwood, Kyle
3              Palou, Alex
4         Newgarden, Josef
5           Malukas, David
6             Dixon, Scott
7            Siegel, Nolan
8        McLaughlin, Scott
9     Lundgaard, Christian
10    Rasmussen, Christian
11       Ferrucci, Santino
12       Rosenqvist, Felix
13           Veekay, Rinus
14         Robb, Sting Ray
15        Rossi, Alexander
16         Simpson, Kyffin
17        Grosjean, Romain
18        Ericsson, Marcus
19           Rahal, Graham
20             Power, Will
21           Foster, Louis
22            Collet, Caio
23        Schumacher, Mick
24           Hauger, Denis
25       Hunter-Reay, Ryan
26      Castroneves, Helio
27            Harvey, Jack
28           Carpenter, Ed
Name: Driver, dtype: object
0        Armstrong, Marcus
1           Kirkwood, Kyle
2              Palou, Alex
3             O'Ward, Pato
4             Dixon, Scott
5     Lundgaard, Christian
6        McLaughlin, Scott
7           Malukas, David
8        Ferrucci, Santino
9            Siegel, Nolan
10        Ericsson, Marcus
11        Newgarden, Josef
12        Rossi, Alexander
13    Rasmussen, Christian
14         Simpson, Kyffin
15       Rosenqvist, Felix
16           Rahal, Graham
17        Grosjean, Romain
18           Veekay, Rinus
19             Power, Will
20         Robb, Sting Ray
21           Foster, Louis
22           Hauger, Denis
23        Schumacher, Mick
24            Collet, Caio
25       Hunter-Reay, Ryan
26           Carpenter, Ed
27      Castroneves, Helio
28            Harvey, Jack
Name: Driver, dtype: object
0        Armstrong, Marcus
1              Palou, Alex
2             O'Ward, Pato
3             Dixon, Scott
4        McLaughlin, Scott
5         Rossi, Alexander
6           Malukas, David
7           Kirkwood, Kyle
8        Rosenqvist, Felix
9            Siegel, Nolan
10        Newgarden, Josef
11    Lundgaard, Christian
12         Simpson, Kyffin
13             Power, Will
14           Veekay, Rinus
15       Ferrucci, Santino
16    Rasmussen, Christian
17        Grosjean, Romain
18        Ericsson, Marcus
19           Rahal, Graham
20         Robb, Sting Ray
21           Foster, Louis
22        Schumacher, Mick
23           Hauger, Denis
24            Collet, Caio
25           Carpenter, Ed
26      Castroneves, Helio
27            Harvey, Jack
28       Hunter-Reay, Ryan
Name: Driver, dtype: object
0        Armstrong, Marcus
1             Dixon, Scott
2             O'Ward, Pato
3          Simpson, Kyffin
4              Palou, Alex
5        McLaughlin, Scott
6     Lundgaard, Christian
7           Kirkwood, Kyle
8         Newgarden, Josef
9           Malukas, David
10    Rasmussen, Christian
11        Ericsson, Marcus
12       Rosenqvist, Felix
13        Grosjean, Romain
14             Power, Will
15           Siegel, Nolan
16           Veekay, Rinus
17       Ferrucci, Santino
18        Rossi, Alexander
19         Robb, Sting Ray
20           Rahal, Graham
21           Foster, Louis
22        Schumacher, Mick
23            Collet, Caio
24           Hauger, Denis
25           Carpenter, Ed
26       Hunter-Reay, Ryan
27      Castroneves, Helio
28            Harvey, Jack
Name: Driver, dtype: object
0         Rossi, Alexander
1              Palou, Alex
2             O'Ward, Pato
3     Lundgaard, Christian
4           Kirkwood, Kyle
5        McLaughlin, Scott
6             Dixon, Scott
7         Grosjean, Romain
8     Rasmussen, Christian
9        Ferrucci, Santino
10        Ericsson, Marcus
11        Newgarden, Josef
12         Simpson, Kyffin
13          Malukas, David
14           Siegel, Nolan
15           Veekay, Rinus
16       Armstrong, Marcus
17           Rahal, Graham
18         Robb, Sting Ray
19       Rosenqvist, Felix
20             Power, Will
21           Foster, Louis
22        Schumacher, Mick
23            Collet, Caio
24           Hauger, Denis
25       Hunter-Reay, Ryan
26           Carpenter, Ed
27      Castroneves, Helio
28            Harvey, Jack
Name: Driver, dtype: object
0        Armstrong, Marcus
1             O'Ward, Pato
2             Dixon, Scott
3              Palou, Alex
4        McLaughlin, Scott
5           Malukas, David
6     Lundgaard, Christian
7         Newgarden, Josef
8            Veekay, Rinus
9         Rossi, Alexander
10       Rosenqvist, Felix
11           Siegel, Nolan
12          Kirkwood, Kyle
13        Ericsson, Marcus
14         Robb, Sting Ray
15    Rasmussen, Christian
16         Simpson, Kyffin
17        Grosjean, Romain
18             Power, Will
19       Ferrucci, Santino
20           Rahal, Graham
21           Foster, Louis
22        Schumacher, Mick
23            Collet, Caio
24           Hauger, Denis
25       Hunter-Reay, Ryan
26           Carpenter, Ed
27      Castroneves, Helio
28            Harvey, Jack
Name: Driver, dtype: object
0        Ferrucci, Santino
1              Palou, Alex
2        McLaughlin, Scott
3             O'Ward, Pato
4     Rasmussen, Christian
5          Simpson, Kyffin
6     Lundgaard, Christian
7           Kirkwood, Kyle
8        Armstrong, Marcus
9           Malukas, David
10        Rossi, Alexander
11        Newgarden, Josef
12            Dixon, Scott
13       Rosenqvist, Felix
14           Siegel, Nolan
15           Veekay, Rinus
16           Rahal, Graham
17        Grosjean, Romain
18         Robb, Sting Ray
19        Ericsson, Marcus
20           Foster, Louis
21           Hauger, Denis
22             Power, Will
23            Collet, Caio
24        Schumacher, Mick
25           Carpenter, Ed
26       Hunter-Reay, Ryan
27            Harvey, Jack
28      Castroneves, Helio
Name: Driver, dtype: object
0        Armstrong, Marcus
1     Lundgaard, Christian
2        McLaughlin, Scott
3              Palou, Alex
4           Kirkwood, Kyle
5             Dixon, Scott
6             O'Ward, Pato
7           Malukas, David
8         Ericsson, Marcus
9        Rosenqvist, Felix
10        Rossi, Alexander
11        Grosjean, Romain
12       Ferrucci, Santino
13        Newgarden, Josef
14         Simpson, Kyffin
15    Rasmussen, Christian
16             Power, Will
17           Rahal, Graham
18           Veekay, Rinus
19         Robb, Sting Ray
20           Siegel, Nolan
21           Foster, Louis
22            Collet, Caio
23           Hauger, Denis
24        Schumacher, Mick
25      Castroneves, Helio
26       Hunter-Reay, Ryan
27           Carpenter, Ed
28            Harvey, Jack
Name: Driver, dtype: object
0         Rossi, Alexander
1              Palou, Alex
2     Lundgaard, Christian
3             O'Ward, Pato
4             Dixon, Scott
5        McLaughlin, Scott
6           Kirkwood, Kyle
7         Ericsson, Marcus
8         Newgarden, Josef
9        Rosenqvist, Felix
10          Malukas, David
11    Rasmussen, Christian
12       Ferrucci, Santino
13           Veekay, Rinus
14       Armstrong, Marcus
15         Robb, Sting Ray
16             Power, Will
17           Siegel, Nolan
18        Grosjean, Romain
19         Simpson, Kyffin
20           Rahal, Graham
21            Collet, Caio
22        Schumacher, Mick
23           Foster, Louis
24           Hauger, Denis
25           Carpenter, Ed
26      Castroneves, Helio
27       Hunter-Reay, Ryan
28            Harvey, Jack
Name: Driver, dtype: object